# Generated by Django 6.0.6 on 2026-06-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('main', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='upatedAt',
            new_name='updatedAt',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'product_size')},
        ),
    ]
